### ISSUE TITLE
有没有验证用户，并获取用户信息的模块

### ISSUE THREAD

**Issue by lovefox666** [HankChow/wework_api#1]
企业微信自建应用，进入应用后，验证用户是否是企业微信的用户，并获取用户的信息。

**Comment by HankChow** [comment]
@lovefox666 
- 验证用户是否是企业微信的用户：能够访问到企业微信自建应用的都是企业微信的用户；
- 获取用户的信息：获取到的消息经过解析之后在 parsed 字典中会有一个 userid 字段，用这个字段的值去查就可以获取到用户信息了。

**Comment by lovefox666** [comment]
因为自建应用本质上都是一个个网址啊。如果直接用浏览器打开，就会绕过企业微信登陆的。

**Comment by HankChow** [comment]
@lovefox666 
访问自建应用的本质确实可以近似理解为对一个 URL 发起请求，但请求这个 URL 并不能视为访问了自建应用。因为一个合法的请求是需要通过 URL 中的一系列 GET 参数对 POST 的数据包进行解密的，只有成功解密才能完成一次请求。而关于每次请求加解密的密钥，只有应用创建者和企业微信服务器知道，只有登录后的企业微信用户完整经过“企业微信客户端-企业微信服务器-应用服务器”这样的路径，才能构造出一个合法的请求，是不会出现绕过的情况的。

**Comment by lovefox666** [comment]
所以需要在企业自建应用的Index页，进行oauth的授权验证，是不是？

**Comment by HankChow** [comment]
是的

**Comment by lovefox666** [comment]
能不能启动一个端口作为企业微信所有自建应用的统一的授权严重，并统一和企业微信后台的API交互？比如获取用户信息，获取用户部门，新增用户等。

**Comment by HankChow** [comment]
对于同一个应用，只能对应一个端口。
